name: Build

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  release:
    types:
      - published
jobs:
  build:
    name: Python ${{ matrix.python-version }} - ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: [ "3.6", "3.7", "3.8", "3.9", "3.10" ]
        laz-backend: [ None, lazrs, laszip ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display Python version
      run: |
          python -c "import sys; print(sys.version)"

    - name: Install With LAZ backend
      if: matrix.laz-backend != 'None'
      run: pip install .[${{ matrix.laz-backend }}]

    - name: Install Without LAZ backend
      if: matrix.laz-backend == 'None'
      run: pip install .

    - name: Run Tests
      run: |
        pip install pytest
        pytest tests
        pytest laspy


  formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Install black
        run: |
          python3 -m pip install setuptools
          python3 -m pip install black==20.8b1

      - name: Run black check
        run: python3 -m black --check laspy



  collect-artifacts:
    name: Package and push release

    needs: [build]

    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: true

    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/checkout@v2
      - name: Source
        shell: bash -l {0}
        run: |
            python3 -m pip install --upgrade pip
            python3 -m pip install setuptools numpy flake8 pytest wheel lazperf
            export PATH=$PATH:/home/runner/.local/bin
            python3 setup.py sdist

      - uses: pypa/gh-action-pypi-publish@master
        name: Publish package

        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
          packages_dir: ./dist
